# 调试配置，当配置为true时，把堆栈跟踪的错误信息也返回给前端
debug:
  errorMsgShow: false

server:
  port: 8080

spring:
  profiles:
    # 默认激活开发环境（可通过启动参数覆盖：--spring.profiles.active=prod）
    active: prod
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
